[WinEventLog://Security]
disabled = 0
index=wineventlog
renderXml = 1

[WinEventLog://System]
disabled = 0
index=wineventlog
renderXml = 1

[WinEventLog://Application]
disabled = 0
index=wineventlog
renderXml = 1

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
index = wineventlog
renderXml = 1

[WinEventLog://Windows PowerShell]
disabled = 0
index = wineventlog
renderXml = 1

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = wineventlog
renderXml = 1
